# Generated by Django 3.1.5 on 2021-01-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('adminEmail', models.CharField(max_length=100)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zpiapi.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('index', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('isTeamAdmin', models.BooleanField()),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zpiapi.team')),
            ],
        ),
    ]
