# Generated by Django 3.1.5 on 2021-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpiapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromUser', models.CharField(max_length=60)),
                ('toUser', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=150)),
                ('msgLines', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[(0, 'Normal'), (1, 'Invitation')], default=0, max_length=20)),
                ('isRead', models.BooleanField()),
            ],
        ),
    ]
