# Generated by Django 3.1.5 on 2021-01-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zpiapi', '0004_auto_20210114_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgLines',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='isTeamAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='teamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zpiapi.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zpiapi.teacher'),
        ),
    ]
