# Generated by Django 3.1.5 on 2021-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpiapi', '0005_auto_20210114_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('accountType', models.CharField(choices=[('0', 'Student'), ('1', 'Lecturer')], default='0', max_length=20)),
            ],
        ),
    ]
