# Generated by Django 3.1.5 on 2021-01-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zpiapi', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zpiapi.team'),
        ),
    ]
